{{- if .Values.secretProviderClass.enabled }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ template "appname" . }}
spec:
  provider: {{ .Values.secretProviderClass.provider }}
  secretObjects: {{- toYaml .Values.secretProviderClass.secretObjects | nindent 4 }}
  parameters:
    usePodIdentity: "{{ .Values.secretProviderClass.parameters.usePodIdentity }}"
    useVMManagedIdentity: "{{ .Values.secretProviderClass.parameters.useVMManagedIdentity }}"
    userAssignedIdentityID: "{{ .Values.secretProviderClass.parameters.userAssignedIdentityID }}"
    keyvaultName: "{{ .Values.secretProviderClass.parameters.keyvaultName }}"
    objects: |
      array:
      {{- range .Values.secretProviderClass.parameters.objects.array }}
        - |
          {{ . | nindent 10 }}
      {{- end }}
    tenantId: "{{ .Values.secretProviderClass.parameters.tenantId }}"
{{- end }}