{{- if .Values.secret.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "appname" . }}
  labels:
    app: {{ template "appname" . }}
    helm.sh/chart: {{ template "chartname" . }}
    app.kubernetes.io/name: {{ template "appname" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: {{ .Values.application.component | quote }}
type: Opaque
data:
  {{- with .Values.secret.data }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}


