name: 'Helm Create and Publish'
on:
  workflow_dispatch:

jobs:


  helm:
    uses: szirmaibence98/templates/.github/workflows/helm.yml@main
    with:
      release: ${{ github.event.inputs.release == 'true' }}
    secrets:
      ACR_USERNAME: ${{ secrets.ACR_USERNAME }}
      ACR_PASSWORD: ${{ secrets.ACR_PASSWORD }}

