name: 'Helm Create and Publish'
on:
  workflow_dispatch:

jobs:

  gitversion:
    name: 'GitVersion'
    uses: szirmaibence98/templates/.github/workflows/gitversion.yml@main

  helm:
    uses: szirmaibence98/templates/.github/workflows/helm.yml@main
    needs: gitversion
    with:
      repository: $REPOSITORY_NAME
    secrets:
      ACR_USERNAME: ${{ secrets.ACR_USERNAME }}
      ACR_PASSWORD: ${{ secrets.ACR_PASSWORD }}

